ass6: Main.o Producer.o Consumer.o
	gcc -o ass6 Main.o Producer.o Consumer.o
Main.o: Main.c
	gcc -c Main.c
Producer.o: Producer.c 
	gcc -c Producer.c
Consumer.o: Consumer.c
	gcc -c Consumer.c
backup:
	cp *.c/home/2015/rfardo/Projects
